image: zerosuxx/php-dev:7.2.9-cli

stages:
- deploy

deploy:
  stage: deploy
  before_script:
  - echo "deploy to Heroku"
  script:
  - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP.git
  - git push -f heroku v2
